### PR TITLE
Upgrade to python 3.x

### PR DESCRIPTION
**Pull request by josepmy**
Hi,

.values() need be converted to list
map need be converted to list

### CODE REVIEW

**Comment by RedFT** [comment]
Sorry for the delay! I've been pretty busy.

**Comment by josepmy** [comment]
All is correct?

**Comment by RedFT** [comment]
Seems to work fine :smiley:

**Comment by josepmy** [comment]
Great.

I have an issue with the mouse pointer, seems that show a boxed background of garbage on bottom of the mouse pointer. Normally the mouse pointer is an arrow but I get a boxed background with the arrow on top.

Any idea?

**Comment by RedFT** [comment]
I'm not sure. It could be a problem with pygame itself. I haven't looked closely at the mouse pointer on my pc

**Pull request merged**
